name: "Deno to Node Transform"

author: "ryohidaka"

description: "GitHub Actions to convert Deno to npm package using @deno/dnt"

branding:
  color: green
  icon: send

inputs:

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
